version: '3.9'
services:
  fb-integrity:
    build: .
    container_name: fb-integrity
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/app
      - ./data.db:/app/data.db
    restart: unless-stopped
